LOAD DATA
INFILE 'C:\Users\mateo_406767\Desktop\Proyecto_Grupo3\Tables\ICCI_Transaction.csv'
REPLACE
INTO TABLE guest121.ICCI_TRANSACTION
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(	TRANSACTIONID INTEGER EXTERNAL,
	CARDNO INTEGER EXTERNAL,
	DESCRIPTION,
	AMOUNT DECIMAL EXTERNAL,
	DATEOFTRANSACTION DATE
)