LOAD DATA
INFILE 'C:\Users\mateo_406767\Desktop\Proyecto_Grupo3\Tables\ICCI_Customer.csv'
REPLACE
INTO TABLE guest121.ICCI_CUSTOMER
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(	CUSTOMERID INTEGER EXTERNAL,
	NAME,
	ADDRESS,
	PHONE,
	EMAIL,
	USERNAME
)