LOAD DATA
INFILE 'C:\Users\mateo_406767\Desktop\Proyecto_Grupo3\Tables\ICCI_Card.csv'
REPLACE
INTO TABLE guest121.ICCI_CARD
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(	CARDNO INTEGER EXTERNAL,
	PIN INTEGER EXTERNAL,
	SCHEMEID,
	BALANCEAMOUNT DECIMAL EXTERNAL,
	CARDAMOUNT DECIMAL EXTERNAL,
	DATEOFREGISTRATION DATE,
	CUSTOMERID INTEGER EXTERNAL
)