LOAD DATA
INFILE 'C:\Users\mateo_406767\Desktop\Proyecto_Grupo3\Tables\ICCI_Scheme.csv'
REPLACE
INTO TABLE guest121.ICCI_SCHEME
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(	SCHEMEID,
	SCHEMEAMOUNT DECIMAL EXTERNAL,
	MINIMUMAMOUNT DECIMAL EXTERNAL,
	INTERESTRATE DECIMAL EXTERNAL
)