LOAD DATA
INFILE 'C:\Users\mateo_406767\Desktop\Proyecto_Grupo3\Tables\ICCI_BlockedCard.csv'
REPLACE
INTO TABLE guest121.ICCI_BLOCKEDCARD
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(	BLOCKID INTEGER EXTERNAL,
	CARDNO INTEGER EXTERNAL,
	DATEOFBLOCK DATE,
	DESCRIPTION,
	STATUS
)